// AUTO-GENERATED by scripts/gen-photo-manifest.mjs — do not edit by hand.
// Re-run: node scripts/gen-photo-manifest.mjs  (also runs on `npm run build`)
// 77 photos across 6 folders.

export const PHOTO_MANIFEST = {
  "book-exhibitions": [
    "/assets/book-exhibitions/29136746_1739484626112723_3652014999640997888_n.jpg",
    "/assets/book-exhibitions/476328447_9312922092102234_410943315551814551_n.jpg",
    "/assets/book-exhibitions/476330357_9312921932102250_855966326791051351_n.jpg",
    "/assets/book-exhibitions/476459579_9312921882102255_3808097486863101668_n.jpg",
    "/assets/book-exhibitions/481961603_9450591995001909_1067827319389844254_n.jpg",
    "/assets/book-exhibitions/486399426_9593312310729876_6359865829360089751_n.jpg",
    "/assets/book-exhibitions/486476985_9597642143630226_3684020982132248313_n.jpg",
    "/assets/book-exhibitions/486615249_9608447689216338_4249087752542057395_n.jpg",
    "/assets/book-exhibitions/486824966_9597642150296892_4654993366848073674_n.jpg",
    "/assets/book-exhibitions/487037949_9608447875882986_6221407690205458303_n.jpg",
    "/assets/book-exhibitions/487300892_9608447699216337_6902240018658023548_n.jpg",
    "/assets/book-exhibitions/487311611_9593312317396542_4342858454479486184_n.jpg",
    "/assets/book-exhibitions/488892346_9644645158929924_8043564324817012697_n.jpg",
    "/assets/book-exhibitions/558683569_24887900544177804_4782967480336102238_n.jpg",
    "/assets/book-exhibitions/629056832_26099031313064715_1929802501588452651_n.jpg",
    "/assets/book-exhibitions/638374167_26096745526626627_5497409166795054033_n.jpg",
    "/assets/book-exhibitions/65462838_2416757721718740_4008066512874110976_n.jpg",
    "/assets/book-exhibitions/65834218_2416756261718886_1492275714001469440_n.jpg",
    "/assets/book-exhibitions/66179402_2416758471718665_9084138976758988800_n.jpg",
    "/assets/book-exhibitions/66487314_2416756965052149_4024981528604835840_n.jpg"
  ],
  "highlights/tree-plantation-drive-2026": [
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-01.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-02.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-03.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-04.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-05.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-06.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-07.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-08.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-09.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-10.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-11.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-12.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-13.jpg"
  ],
  "tree-plantation/prakriti-mitra-abhiyan": [
    "/assets/tree-plantation/prakriti-mitra-abhiyan/31939538_1799705610090624_6124962593497939968_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/31956252_1799705656757286_207449613341294592_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/31960605_1799705453423973_8050254986136780800_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/31961696_1799705330090652_7741074330745831424_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/34368001_448276162285701_5341010759943979008_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/34370763_448276242285693_5034902277479989248_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/34503470_448277125618938_8240854154285678592_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/34563626_1015328775308869_7533112173187301376_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/41869163_1983022618425588_4051770991976644608_n.jpg",
    "/assets/tree-plantation/prakriti-mitra-abhiyan/42107966_1983022791758904_6168359467042734080_n.jpg"
  ],
  "gau-seva": [
    "/assets/gau-seva/1.jpg",
    "/assets/gau-seva/2.jpg",
    "/assets/gau-seva/3.jpg",
    "/assets/gau-seva/4.jpg",
    "/assets/gau-seva/480741911_673539231906362_2607419836205428928_n.jpg",
    "/assets/gau-seva/481082715_681013211158964_6985804106298569691_n.jpg",
    "/assets/gau-seva/WhatsApp Image 2026-06-27 at 12.07.36 AM (1).jpeg",
    "/assets/gau-seva/gau-puja.jpg",
    "/assets/gau-seva/gau.jpg",
    "/assets/gau-seva/gaushala.jpg",
    "/assets/gau-seva/gaushala1.jpg"
  ],
  "yagya": [
    "/assets/yagya/11-kund-gayatri-mahayagya-2026-01.jpg",
    "/assets/yagya/11-kund-gayatri-mahayagya-2026-03.jpg",
    "/assets/yagya/11-kund-gayatri-mahayagya-2026-04.jpg",
    "/assets/yagya/39468327_1944857708908746_312695454762532864_n.jpg",
    "/assets/yagya/599273664_25485821067719079_8225836740638127748_n.jpg",
    "/assets/yagya/triveni-mahasangam-2026-07.jpg",
    "/assets/yagya/triveni-mahasangam-2026-09.jpg",
    "/assets/yagya/yagya1.jpg",
    "/assets/yagya/yagya2.jpg"
  ],
  "yagya/deepyagya": [
    "/assets/yagya/deepyagya/483660631_687107507216201_1128914289342259091_n.jpg",
    "/assets/yagya/deepyagya/483746114_687107413882877_6794369578545476439_n.jpg",
    "/assets/yagya/deepyagya/484771867_687107510549534_4870158932982505478_n.jpg",
    "/assets/yagya/deepyagya/591826006_896758579584425_111075302826200255_n.jpg",
    "/assets/yagya/deepyagya/593932094_896758149584468_8502820640965827047_n.jpg",
    "/assets/yagya/deepyagya/64538821_2390917840969395_44285051306770432_n.jpg",
    "/assets/yagya/deepyagya/64647047_2390918104302702_5843990226745163776_n.jpg",
    "/assets/yagya/deepyagya/64885952_2390918034302709_7433326424905220096_n.jpg",
    "/assets/yagya/deepyagya/65233791_2390917927636053_6896348675593732096_n.jpg",
    "/assets/yagya/deepyagya/78596598_2696038333790676_1759971512208588800_n.jpg",
    "/assets/yagya/deepyagya/79183777_2724722644255578_1126218503221673984_n.jpg",
    "/assets/yagya/deepyagya/gayatri-jayanti-2026-05.jpg",
    "/assets/yagya/deepyagya/makar sankranti.jpg",
    "/assets/yagya/deepyagya/yagya.jpg"
  ]
};
