// AUTO-GENERATED by scripts/gen-photo-manifest.mjs — do not edit by hand.
// Re-run: node scripts/gen-photo-manifest.mjs  (also runs on `npm run build`)
// 44 photos across 3 folders.

export const PHOTO_MANIFEST = {
  "book-exhibitions": [
    "/assets/book-exhibitions/29136746_1739484626112723_3652014999640997888_n.jpg",
    "/assets/book-exhibitions/476328447_9312922092102234_410943315551814551_n.jpg",
    "/assets/book-exhibitions/476330357_9312921932102250_855966326791051351_n.jpg",
    "/assets/book-exhibitions/476459579_9312921882102255_3808097486863101668_n.jpg",
    "/assets/book-exhibitions/481961603_9450591995001909_1067827319389844254_n.jpg",
    "/assets/book-exhibitions/486399426_9593312310729876_6359865829360089751_n.jpg",
    "/assets/book-exhibitions/486476985_9597642143630226_3684020982132248313_n.jpg",
    "/assets/book-exhibitions/486615249_9608447689216338_4249087752542057395_n.jpg",
    "/assets/book-exhibitions/486824966_9597642150296892_4654993366848073674_n.jpg",
    "/assets/book-exhibitions/487037949_9608447875882986_6221407690205458303_n.jpg",
    "/assets/book-exhibitions/487300892_9608447699216337_6902240018658023548_n.jpg",
    "/assets/book-exhibitions/487311611_9593312317396542_4342858454479486184_n.jpg",
    "/assets/book-exhibitions/488892346_9644645158929924_8043564324817012697_n.jpg",
    "/assets/book-exhibitions/558683569_24887900544177804_4782967480336102238_n.jpg",
    "/assets/book-exhibitions/629056832_26099031313064715_1929802501588452651_n.jpg",
    "/assets/book-exhibitions/638374167_26096745526626627_5497409166795054033_n.jpg",
    "/assets/book-exhibitions/65462838_2416757721718740_4008066512874110976_n.jpg",
    "/assets/book-exhibitions/65834218_2416756261718886_1492275714001469440_n.jpg",
    "/assets/book-exhibitions/66179402_2416758471718665_9084138976758988800_n.jpg",
    "/assets/book-exhibitions/66487314_2416756965052149_4024981528604835840_n.jpg"
  ],
  "highlights/tree-plantation-drive-2026": [
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-01.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-02.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-03.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-04.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-05.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-06.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-07.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-08.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-09.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-10.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-11.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-12.jpg",
    "/assets/highlights/tree-plantation-drive-2026/tree-plantation-drive-2026-13.jpg"
  ],
  "gau-seva": [
    "/assets/gau-seva/1.jpg",
    "/assets/gau-seva/2.jpg",
    "/assets/gau-seva/3.jpg",
    "/assets/gau-seva/4.jpg",
    "/assets/gau-seva/480741911_673539231906362_2607419836205428928_n.jpg",
    "/assets/gau-seva/481082715_681013211158964_6985804106298569691_n.jpg",
    "/assets/gau-seva/WhatsApp Image 2026-06-27 at 12.07.36 AM (1).jpeg",
    "/assets/gau-seva/gau-puja.jpg",
    "/assets/gau-seva/gau.jpg",
    "/assets/gau-seva/gaushala.jpg",
    "/assets/gau-seva/gaushala1.jpg"
  ]
};
